// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Wh1kP1VSOkII9lG_Jp9Iqi6QZOyXaWk',
    appId: '1:737966527599:web:4f6e6124faf04244a4699a',
    messagingSenderId: '737966527599',
    projectId: 'task-6-ebazaar',
    authDomain: 'task-6-ebazaar.firebaseapp.com',
    storageBucket: 'task-6-ebazaar.appspot.com',
    measurementId: 'G-GKBYG7MRZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa_3l07j1R7wE5UdV_rbRqpXM_9LA2VZg',
    appId: '1:737966527599:android:403728da49a91b56a4699a',
    messagingSenderId: '737966527599',
    projectId: 'task-6-ebazaar',
    storageBucket: 'task-6-ebazaar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn7y-QbHNpuej9aH0oEJk8-ys6DRwM4kE',
    appId: '1:737966527599:ios:60f3bd19968a5b1ba4699a',
    messagingSenderId: '737966527599',
    projectId: 'task-6-ebazaar',
    storageBucket: 'task-6-ebazaar.appspot.com',
    iosBundleId: 'com.nosh.task6ECommerceEBazaar',
  );

}